kindness_acts = [
    "Compliment a stranger genuinely 😊",
    "Hold the door open for someone 🚪",
    "Write a kind note for a friend or family member 📝",
    "Donate unused clothes to charity 👕",
    "Let someone go ahead of you in line ⏳",
    "Send a supportive message to a friend 📩",
    "Leave a positive review for a local business ⭐",
    "Pick up litter in your neighborhood 🗑️",
    "Smile at people you pass by today 😊",
    "Call a family member just to say hello 📞",
    "Offer to help a coworker with a task 💼",
    "Pay for someone’s coffee or meal ☕",
    "Bake something for your neighbors 🍪",
    "Send an anonymous thank-you note 💌",
    "Encourage someone who looks down 💬",
    "Leave a kind message on a sticky note 📜",
    "Donate books to a local library 📚",
    "Help a tourist with directions 🗺️",
    "Give an honest, kind compliment 💖",
    "Volunteer at a shelter or charity 🏠",
    "Check in on an elderly neighbor 👵",
    "Share your umbrella in the rain ☔",
    "Offer your seat on public transport 🚋",
    "Share positive news instead of complaints 📰",
    "Let someone merge in traffic 🚗",
    "Send a surprise gift to a friend 🎁",
    "Listen to someone without interrupting 👂",
    "Send a thank-you message to a teacher 👨‍🏫",
    "Bring snacks for coworkers or classmates 🍏",
    "Send a handwritten letter instead of a text ✍️",
    "Teach someone a skill you’re good at 🎨",
    "Offer to babysit for free 🍼",
    "Donate blood if you're able 🩸",
    "Send flowers to a hospital patient 🌻",
    "Leave a big tip for a server 💰",
    "Return a lost item to its owner 🔑",
    "Write a recommendation for a colleague ✨",
    "Help someone carry heavy groceries 🛍️",
    "Thank a delivery person or mail carrier 📦",
    "Organize a local clean-up event 🌍",
    "Share your favorite book with a friend 📖",
    "Help someone with tech issues 💻",
    "Support a small business instead of a big chain 🛒",
    "Introduce two friends who might get along 🤝",
    "Buy extra food and donate it 🍲",
    "Tell a joke to make someone laugh 😂",
    "Leave a nice comment on a social media post 💬",
    "Recycle something instead of throwing it away ♻️",
    "Water a plant that looks thirsty 🌿",
    "Help a student with their studies 📖",
    "Hold the elevator for someone 🚪",
    "Send an appreciation email to a coworker 📧",
    "Apologize sincerely if you’ve hurt someone ❤️",
    "Give directions to someone who looks lost 🧭",
    "Let someone else take the last piece of food 🍕",
    "Offer to take a photo for a couple or group 📷",
    "Make a playlist for a friend who needs cheering up 🎶",
    "Volunteer to walk a neighbor’s dog 🐶",
    "Pay for the toll of the car behind you 🚗",
    "Let a parent with kids cut ahead in line 🏃",
    "Share an inspiring story with someone 📖",
    "Bring reusable bags to the store 🛍️",
    "Put away a misplaced shopping cart 🛒",
    "Help clean up after an event 🧹",
    "Give someone your extra change 💵",
    "Make a handmade gift for someone 🎨",
    "Compliment a child on their creativity 👶",
    "Give up your preferred parking spot 🚘",
    "Support a friend’s project or business 🚀",
    "Encourage someone who’s having a bad day 🌞",
    "Write a positive note in a library book 📖",
    "Tell someone why they matter to you 💕",
    "Pick up trash when you see it 🗑️",
    "Bring coffee or tea for a friend ☕",
    "Celebrate a friend’s success as if it were your own 🎉",
    "Offer to run an errand for a busy friend 🏃‍♂️",
    "Share your WiFi hotspot with someone in need 📶",
    "Help someone reach something on a high shelf 📦",
    "Call your grandparents just to chat ☎️",
    "Be patient with customer service workers ⏳",
    "Buy food for a homeless person 🍞",
    "Write a note of encouragement to a stranger 💌",
    "Be extra kind to a new student or coworker 👋",
    "Offer your charger to someone with a low battery 🔋",
    "Help a friend move houses or rearrange furniture 📦",
    "Buy a treat for your pet or a stray animal 🐾",
    "Listen to someone’s worries without offering advice 🎧",
    "Give a gift card to someone who could use it 🎁",
    "Leave a ‘Have a great day’ note on someone’s car 🚗",
    "Donate school supplies to kids in need 🎒",
    "Help a friend update their resume or profile 📝",
    "Make a donation to a cause you care about 💸",
    "Say ‘thank you’ with eye contact and a smile 😊",
    "Offer free hugs (if appropriate) 🤗",
    "Encourage kids to be kind and respectful ❤️",
    "Offer to take someone’s shopping cart back 🛒",
    "Tell a street musician you appreciate their talent 🎸",
    "Give someone an inspiring book 📚",
    "Let someone borrow something of yours 📦",
    "Tell a friend what you admire about them 💙"
]
